<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Roslynator.Analyzers" Version="4.16.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageVersion>
		<PackageVersion Include="TUnit" Version="1.65.0" />
	</ItemGroup>
</Project>