namespace Claudinine.Mirror;

/// <summary>
/// The per-session retrieval launcher: `run.sh` (+ `run.cmd` twin) written next
/// to the colocated mirror, so digest headers can spell a command that works
/// with NO PATH entry — a claude.ai-hosted plugin may not ship a top-level
/// `bin/`, so in Cowork the binary is never on the Bash tool's PATH.
///
/// The launcher resolves from <see cref="Environment.ProcessPath"/> — re-derived
/// on every pass, so a plugin update or a different install context
/// self-corrects at the next hook. When the running binary sits in the plugin
/// layout (`libexec/&lt;rid&gt;/claudinine`), the launcher targets the ROUTING SHIM
/// (`libexec/claudinine`) rather than the binary itself: the shim selects the
/// RID from `uname` at RUN time, where the binary path bakes the WRITE-time
/// platform — and the two differ whenever the hook's OS is not the shell's
/// (docs/cowork-compatibility.md B5: on Windows a `run.sh` exec'ing a win-x64
/// PE is broken by construction for any POSIX shell that isn't MSYS).
/// Outside that layout (dev builds, tests) the binary itself is the target,
/// as before. Headers invoke it as `sh &lt;path&gt;`, which makes a lost exec bit
/// survivable; the chmod is belt and braces. Regenerated every pass and safe
/// to delete; the colocated GC leaves it alone (unknown extension) and the
/// whole dir dies with the session via SessionDirGc.
///
/// The script also exports CLAUDININE_DIR=&lt;its own directory&gt; so `get` can
/// address this session's mirrors directly instead of globbing every project —
/// faster, and immune to two sessions with colliding id prefixes.
/// </summary>
internal static class Launcher
{
    /// <summary>Env var the launcher sets; GetVerb's direct-addressing fast path.</summary>
    public const string DirEnvVar = "CLAUDININE_DIR";

    public static string PathFor(string transcriptPath) =>
        Path.Combine(MirrorLocator.ClaudinineDirFor(transcriptPath), "run.sh");

    /// <summary>
    /// The form digest headers embed: absolute, forward slashes only. Headers
    /// invoke it as `sh "&lt;path&gt;"` from the Bash tool, which on Windows is Git
    /// Bash — where backslashes are escape characters, while `C:/…` works in
    /// both worlds.
    /// </summary>
    public static string HeaderPathFor(string transcriptPath) =>
        Path.GetFullPath(PathFor(transcriptPath)).Replace('\\', '/');

    public static void EnsureCurrent(string transcriptPath)
    {
        if (Environment.ProcessPath is string binary)
            EnsureCurrent(transcriptPath, binary);
    }

    /// <summary>Binary seam for tests (ProcessPath is the test host there).</summary>
    internal static void EnsureCurrent(string transcriptPath, string binary)
    {
        // Fail-safe like LoadStamp.Write: a launcher we cannot write only costs
        // retrieval convenience, never a broken pass.
        try
        {
            (string shTarget, string cmdTarget) = ResolveTargets(binary);
            string dir = MirrorLocator.ClaudinineDirFor(transcriptPath);
            Directory.CreateDirectory(dir);
            WriteIfChanged(Path.Combine(dir, "run.sh"), ShellScript(shTarget), unixMode: true);
            WriteIfChanged(Path.Combine(dir, "run.cmd"), CmdScript(cmdTarget), unixMode: false);
        }
        catch
        {
        }
    }

    /// <summary>
    /// Prefer the plugin's routing shims over the concrete binary (see class
    /// doc): a binary at `…/libexec/&lt;rid&gt;/claudinine[.exe]` resolves to
    /// `…/libexec/claudinine` for run.sh and `…/libexec/claudinine.cmd` for
    /// run.cmd — each only when that shim actually exists, so a dev tree or a
    /// hand-pruned install falls back to the binary that is provably there.
    /// </summary>
    private static (string ShTarget, string CmdTarget) ResolveTargets(string binary)
    {
        string shTarget = binary, cmdTarget = binary;
        string? ridDir = Path.GetDirectoryName(Path.GetFullPath(binary));
        string? libexec = ridDir is null ? null : Path.GetDirectoryName(ridDir);
        if (libexec is not null
            && Path.GetFileName(libexec).Equals("libexec", StringComparison.OrdinalIgnoreCase))
        {
            string shim = Path.Combine(libexec, "claudinine");
            string shimCmd = Path.Combine(libexec, "claudinine.cmd");
            if (File.Exists(shim))
                shTarget = shim;
            if (File.Exists(shimCmd))
                cmdTarget = shimCmd;
        }
        return (shTarget, cmdTarget);
    }

    private static string ShellScript(string binary) =>
        "#!/bin/sh\n" +
        "# claudinine retrieval launcher — regenerated by every compaction pass; the\n" +
        "# digest headers in this session's transcript invoke it by absolute path so\n" +
        "# retrieval needs no PATH entry. Safe to delete; the next pass rewrites it.\n" +
        "CLAUDININE_DIR=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\n" +
        "export CLAUDININE_DIR\n" +
        $"exec \"{binary.Replace('\\', '/')}\" \"$@\"\n";

    private static string CmdScript(string binary) =>
        "@echo off\r\n" +
        "rem claudinine retrieval launcher (Windows twin of run.sh).\r\n" +
        "set \"CLAUDININE_DIR=%~dp0\"\r\n" +
        $"\"{binary}\" %*\r\n";

    /// <summary>
    /// Idempotent write: byte-compare first so a no-op pass never touches mtime,
    /// then temp + atomic rename, same discipline as the rest of the codebase.
    /// </summary>
    private static void WriteIfChanged(string path, string content, bool unixMode)
    {
        byte[] bytes = new UTF8Encoding(false).GetBytes(content);
        if (File.Exists(path) && File.ReadAllBytes(path).AsSpan().SequenceEqual(bytes))
            return;
        string tmp = path + ".tmp";
        File.WriteAllBytes(tmp, bytes);
        if (unixMode && !OperatingSystem.IsWindows())
        {
            try
            {
                File.SetUnixFileMode(tmp, // 755
                    UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
                    UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
                    UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
            }
            catch
            {
                // Headers invoke via `sh`, so a lost exec bit is survivable.
            }
        }
        File.Move(tmp, path, overwrite: true);
    }
}
