namespace Claudinine.Mirror;

/// <summary>
/// The per-session retrieval launcher: `run.sh` (+ `run.cmd` twin) written next
/// to the colocated mirror, so digest headers can spell a command that works
/// with NO PATH entry — a claude.ai-hosted plugin may not ship a top-level
/// `bin/`, so in Cowork the binary is never on the Bash tool's PATH.
///
/// The launcher targets <see cref="Environment.ProcessPath"/> — the actually
/// running AOT binary, not the routing shim — re-resolved on every pass, so a
/// plugin update or a different install context self-corrects at the next hook.
/// Headers invoke it as `sh &lt;path&gt;`, which makes a lost exec bit survivable;
/// the chmod is belt and braces. Regenerated every pass and safe to delete;
/// the colocated GC leaves it alone (unknown extension) and the whole dir dies
/// with the session via SessionDirGc.
///
/// The script also exports CLAUDININE_DIR=&lt;its own directory&gt; so `get` can
/// address this session's mirrors directly instead of globbing every project —
/// faster, and immune to two sessions with colliding id prefixes.
/// </summary>
internal static class Launcher
{
    /// <summary>Env var the launcher sets; GetVerb's direct-addressing fast path.</summary>
    public const string DirEnvVar = "CLAUDININE_DIR";

    public static string PathFor(string transcriptPath) =>
        Path.Combine(MirrorLocator.ClaudinineDirFor(transcriptPath), "run.sh");

    /// <summary>
    /// The form digest headers embed: absolute, forward slashes only. Headers
    /// invoke it as `sh "&lt;path&gt;"` from the Bash tool, which on Windows is Git
    /// Bash — where backslashes are escape characters, while `C:/…` works in
    /// both worlds.
    /// </summary>
    public static string HeaderPathFor(string transcriptPath) =>
        Path.GetFullPath(PathFor(transcriptPath)).Replace('\\', '/');

    public static void EnsureCurrent(string transcriptPath)
    {
        if (Environment.ProcessPath is string binary)
            EnsureCurrent(transcriptPath, binary);
    }

    /// <summary>Binary seam for tests (ProcessPath is the test host there).</summary>
    internal static void EnsureCurrent(string transcriptPath, string binary)
    {
        // Fail-safe like LoadStamp.Write: a launcher we cannot write only costs
        // retrieval convenience, never a broken pass.
        try
        {
            string dir = MirrorLocator.ClaudinineDirFor(transcriptPath);
            Directory.CreateDirectory(dir);
            WriteIfChanged(Path.Combine(dir, "run.sh"), ShellScript(binary), unixMode: true);
            WriteIfChanged(Path.Combine(dir, "run.cmd"), CmdScript(binary), unixMode: false);
        }
        catch
        {
        }
    }

    private static string ShellScript(string binary) =>
        "#!/bin/sh\n" +
        "# claudinine retrieval launcher — regenerated by every compaction pass; the\n" +
        "# digest headers in this session's transcript invoke it by absolute path so\n" +
        "# retrieval needs no PATH entry. Safe to delete; the next pass rewrites it.\n" +
        "CLAUDININE_DIR=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\n" +
        "export CLAUDININE_DIR\n" +
        $"exec \"{binary.Replace('\\', '/')}\" \"$@\"\n";

    private static string CmdScript(string binary) =>
        "@echo off\r\n" +
        "rem claudinine retrieval launcher (Windows twin of run.sh).\r\n" +
        "set \"CLAUDININE_DIR=%~dp0\"\r\n" +
        $"\"{binary}\" %*\r\n";

    /// <summary>
    /// Idempotent write: byte-compare first so a no-op pass never touches mtime,
    /// then temp + atomic rename, same discipline as the rest of the codebase.
    /// </summary>
    private static void WriteIfChanged(string path, string content, bool unixMode)
    {
        byte[] bytes = new UTF8Encoding(false).GetBytes(content);
        if (File.Exists(path) && File.ReadAllBytes(path).AsSpan().SequenceEqual(bytes))
            return;
        string tmp = path + ".tmp";
        File.WriteAllBytes(tmp, bytes);
        if (unixMode && !OperatingSystem.IsWindows())
        {
            try
            {
                File.SetUnixFileMode(tmp, // 755
                    UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
                    UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
                    UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
            }
            catch
            {
                // Headers invoke via `sh`, so a lost exec bit is survivable.
            }
        }
        File.Move(tmp, path, overwrite: true);
    }
}
